// Fetch all items
export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';

// Fetch featured items
export const FETCH_FEATURED_REQUEST = 'FETCH_FEATURED_REQUEST';
export const FETCH_FEATURED_SUCCESS = 'FETCH_FEATURED_SUCCESS';
export const FETCH_FEATURED_FAILURE = 'FETCH_FEATURED_FAILURE';

// Fetch new arrivals
export const FETCH_NEW_ARRIVALS_REQUEST = 'FETCH_NEW_ARRIVALS_REQUEST';
export const FETCH_NEW_ARRIVALS_SUCCESS = 'FETCH_NEW_ARRIVALS_SUCCESS';
export const FETCH_NEW_ARRIVALS_FAILURE = 'FETCH_NEW_ARRIVALS_FAILURE';

// Fetch sale items
export const FETCH_SALE_REQUEST = 'FETCH_SALE_REQUEST';
export const FETCH_SALE_SUCCESS = 'FETCH_SALE_SUCCESS';
export const FETCH_SALE_FAILURE = 'FETCH_SALE_FAILURE';

// UI state
export const SET_QUERY = 'SET_QUERY';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';
export const SET_ACTIVE_SECTION = 'SET_ACTIVE_SECTION';
