// Fetch user orders
export const FETCH_USER_ORDERS_REQUEST = 'FETCH_USER_ORDERS_REQUEST';
export const FETCH_USER_ORDERS_SUCCESS = 'FETCH_USER_ORDERS_SUCCESS';
export const FETCH_USER_ORDERS_FAILURE = 'FETCH_USER_ORDERS_FAILURE';

// Track order
export const TRACK_ORDER_REQUEST = 'TRACK_ORDER_REQUEST';
export const TRACK_ORDER_SUCCESS = 'TRACK_ORDER_SUCCESS';
export const TRACK_ORDER_FAILURE = 'TRACK_ORDER_FAILURE';

// Clear tracking
export const CLEAR_TRACKING = 'CLEAR_TRACKING';
